### ISSUE TITLE
NodeifyWP missing files after composer install

### ISSUE THREAD

**Issue by danielck** [10up/twentysixteenreact#3]
When attempting to load the twentysixteenreact theme, if failed with this error

```
Warning: require_once(/var/www/html/wp-content/themes/twentysixteenreact/vendor/10up/nodeifywp/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/wp-content/themes/twentysixteenreact/vendor/10up/nodeifywp/App.php on line 144

Fatal error: require_once(): Failed opening required '/var/www/html/wp-content/themes/twentysixteenreact/vendor/10up/nodeifywp/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/wp-content/themes/twentysixteenreact/vendor/10up/nodeifywp/App.php on line 144
```

Line 144 of App.php does this:
`require_once __DIR__ . '/vendor/autoload.php';`

The whole vendor directory was missing, which could be fixed by running `composer install` within the vendor/10up/nodeifywp directory itself, but surely running composer separately for each dependency should not be required?

**Comment by tlovett1** [comment]
This one should be fixed. Can you confirm?
