### ISSUE TITLE
Showing Fatal error: Uncaught V8JsScriptException:  on file App.php:53 

### ISSUE THREAD

**Issue by alicoolpro** [10up/twentysixteenreact#7]
Here is the error showing...

Fatal error: Uncaught V8JsScriptException: 2:3: SyntaxError: Unexpected token import in C:\xampp\htdocs\wp-nodify\wp-content\themes\twentysixteenreact\vendor\10up\nodeifywp\App.php:53 Stack trace: #0 C:\xampp\htdocs\wp-nodify\wp-content\themes\twentysixteenreact\vendor\10up\nodeifywp\App.php(53): V8Js->executeString(''use strict';\n\n...', '2') #1 C:\xampp\htdocs\wp-nodify\wp-includes\class-wp-hook.php(298): NodeifyWP\App->render('') #2 C:\xampp\htdocs\wp-nodify\wp-includes\class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #3 C:\xampp\htdocs\wp-nodify\wp-includes\plugin.php(453): WP_Hook->do_action(Array) #4 C:\xampp\htdocs\wp-nodify\wp-includes\template-loader.php(12): do_action('template_redire...') #5 C:\xampp\htdocs\wp-nodify\wp-blog-header.php(19): require_once('C:\\xampp\\htdocs...') #6 C:\xampp\htdocs\wp-nodify\index.php(17): require('C:\\xampp\\htdocs...') #7 {main} thrown in C:\xampp\htdocs\wp-nodify\wp-content\themes\twentysixteenreact\vendor\10up\nodeifywp\App.php on line 53

**Comment by alicoolpro** [comment]
Sorry for troubled you, but the issue has been resolved. But one concern i am having with the build i am using of twentysixteenreact is much slower that the official twentysixteen theme.

**Comment by tlovett1** [comment]
Our benchmarks show this is production ready (see README.md)
