### ISSUE TITLE
`docker-compose up` fails at Step 13

### ISSUE THREAD

**Issue by ockham** [10up/twentysixteenreact#9]
...with `cp: cannot stat 'out.gn/x64.release/lib*.so': No such file or directory`

**Comment by tlovett1** [comment]
Can you try again?

**Comment by ockham** [comment]
Still no luck, even after a `git pull`; tho I think [the relevant line](https://github.com/10up/twentysixteenreact/blob/bcf74b7365252c03aaf6911a6ac08e6882b6d00f/Dockerfile#L25) wasn't changed by your latest commits anyway.

I wonder if `docker-compose` is re-using an outdated image somewhere for either of us. Since I ran into the issue right after a fresh checkout, is it possible that those files are lingering in an image in your setup (that predates the current state of the `Dockerfile`)? (Maybe try `docker-compose up --force-recreate` -- for me, that yielded the same error as before FWIW.)

**Comment by ockham** [comment]
Closing in favor of 10up/php-v8#1
